import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Provider from "@/Providers/Providers";

export const metadata: Metadata = {
  title: {
    absolute: "Game store",
    template: `%s | Game store`,
  },
  description: "Generated by create next app",
};

const getisNotoSans = Noto_Sans({
  weight: ["400", "500", "600", "700"],
  variable: "--font-russo",
  subsets: ["latin", "cyrillic"],
  display: "swap",
  style: ["normal"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={getisNotoSans.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
